### ISSUE TITLE
Improve test FQNs

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt#3259]
### Describe the feature

The FQNs for schema + data tests today are sort of silly, especially schema tests.
```
$ dbt ls --resource-type test
my_other_project.data_test.my_test
my_project.schema_test.accepted_values_model_a_id__1__2__3
my_project.subfolder.data_test.my_test
my_project.schema_test.my_test_model_a_
```
This means that, from the project file, these tests have to be configured sort of awkardly:
```yml
tests:
  my_project:
    schema_test:
      my_test_model_a_:
        +enabled: false
  my_other_project:
    data_test:
      +severity: warn
```

Ideally, we'd remove the data test / schema test nomenclature (#3234) and rationalize the FQNs.

- ~Bespoke~ Singular test FQNs are straightforward: just project + file path
- Generic test blocks: just project + name? Or fuller file-path FQNs?
- Specific instantiations of generic tests: ideally, this might include target FQNs (e.g. `my_project.models.subfolder.model_a.id.unique`), to enable things like:
```yml
tests:
  models:
    subfolder:
      model_a:
        +enabled: false
        id:
          +enabled: true
```
But that may be overkill for the first cut of this! The main use case for configuring tests from `dbt_project.yml` is disabling/controlling behavior from a package. Maybe neater package-level FQNs is all we need.

In any case, we could start making the adjustments here:
https://github.com/fishtown-analytics/dbt/blob/7ec5c122e17ab7e1a5dd1e1cab36527159564a0f/core/dbt/parser/schemas.py#L439-L444
