### ISSUE TITLE
User-defined default selection criteria

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt#3448]
_Credit where due: This was @aescay's idea many months ago!_

### Describe the feature

We've increasingly heard a desire from community members to limit `dbt run` in development to only a subset of their project, or to always exclude a set of infrequently run models. Trying to solve for this with `enabled` gets tricky quickly, because disabled resources cannot participate in the DAG and will raise dependency errors accordingly.

Instead, what if there were a way to redefine the default selection criteria? I think the right construct for this is a [yaml selector](https://docs.getdbt.com/reference/node-selection/yaml-selectors) (as in `selectors.yml`). We could support a new selector property, `default: true|false`, or check for a selector named `default`. The former is almost certaintly better, we'd just need to raise an error if multiple selectors have `default: true`.

If specified, that selector should override the default includes + excludes defined here:

https://github.com/fishtown-analytics/dbt/blob/abe8e839458d0288f76cb6950e79c77e3b1627cc/core/dbt/graph/cli.py#L22-L23

Then, `dbt run` would have the same effect as `dbt run --selector my_default_selector`.

### Questions

1. How to combine the user-defined default with additional selection criteria passed via CLI syntax? Should the two be combined, or should the CLI criteria entirely override the default? I'm leaning toward total override for two reasons:
    - It's what happens today: `dbt ls` really means ` dbt ls --select fqn:* source:* exposure:*`, as soon as the user says `-s something_else`, the command becomes `dbt ls -s something_else`
    - Override feels like the only way to make sense of `dbt ls --selector not_the_default`
2. Can we support different default selectors in different environments? I think it makes a lot of sense to perma-exclude certain models in development, but still select them in production. As it turns out, `selectors.yml` already supports Jinja today, so this could be as simple as:
```yml
selectors:
  - name: prod
    description: Select everything in prod
    default: "{{ target.name == 'prod' | as_bool }}"
    definition: 'fqn:* source:* exposure:*'
  - name: dev
    description: Avoid unpleasant surprises in dev
    default: "{{ target.name == 'dev' | as_bool }}"
    definition:
      union:
        - 'fqn:* source:* exposure:*'
        - exclude:
            - unpleasant
            - surprises
```
