### ISSUE TITLE
[Spike] Configs in schema work

### ISSUE THREAD

**Issue by leahwicz** [dbt-labs/dbt#3515]
This is in reference to issue https://app.zenhub.com/workspace/o/fishtown-analytics/dbt/issues/2401

**Goal/Exit Criteria**: Take 2-3 days to dig into the issue, identify a plan for what changes need to be made and the time it would take so that we can make a decision on whether to further pursue it. A list of the difficult/unknown items we would need to implement.

**Comment by jtcohen6** [comment]
I know that #2401 has a lot going on in it, and it reads more as a conversation than a set of requirements. So I'll quickly summarize the thrust of this larger initiative below.

--------

### User stories

As a dbt user, I shouldn't have to think about what's a config and what's a property, or whether something can go in `dbt_project.yml` vs. in-file `config()` vs. `everything_else.yml`. I should be able to define these things wherever & however I want.

Beyond a convenience, this becomes crucial if I want to override properties defined in a package, since I can't edit the yaml files directly—I can only override configs in `dbt_project.yml`.

As the team maintaining dbt, this also gives us the opportunity to significantly clean up the codebase around config inheritance and property patching, which are two very different things today. It also gives us the opportunity to remove [some rationalizations from the docs](https://docs.getdbt.com/reference/declaring-properties).

### Examples

Say I'm creating a model, and I want to add a description. Why not:

```sql
# models/my_model.sql

{{ config(description = 'This is my model') }}

select 1 as fun
```

Alternatively, if I *hate* the kwarg-y `config()` syntax, I could set all my model's config-properties in yaml instead:

```yaml
# models/schema.yml
version: 2

models:
 - name: my_model
   config:
      materialized: view
      bind: false
   meta: ...  # for historical reasons, we'll need to support certain keys here
```

Or say I'm configuring the location of `sources`, and I want to override *all* the sources in my project. Instead of manually overriding each one, setting it to a dynamic value, or using a `var`, I could simply do this in `dbt_project.yml`:

```yaml
models:
  +database: ci_db   # possible today (config)

sources:
  +database: ci_db   # not possible today (property)
```

If we're already going to go through the trouble of adding `config:` dictionaries, to make this syntax more consistent, we could also offer it as an alternative to the [`+` prefix](https://docs.getdbt.com/reference/resource-configs/plus-prefix), which many newer users find confusing:

```yaml
models:
  config:
    database: ci_db

sources:
  config:
    database: ci_db
```

### Complexities

- This gets into some very thorny code, where I haven't spelunked much personally. There's prior art in the form of `tags`, which are the only config-property hybrid today.
- What to do about overlap? If a user sets the same config multiple times at the same "specificity level," i.e. in a model's `config()` and also in its yaml properties, I think we should raise an error.
- Let's figure out a sensible way to represent this in `manifest.json`. Configs show up in the manifest within `node.configs`, whereas properties are node-level keys.
- Let's be choosy in what we support as a [node selection method](https://docs.getdbt.com/reference/node-selection/methods#the-config-method) (`config.kwarg:value`). I don't think selecting models based on `config.description:` makes a lot of sense!
