### ISSUE TITLE
Missing semicolon in dbt_header documentation

### ISSUE THREAD

**Issue by GuillaumeLegoy** [dbt-labs/dbt#3534]
Hello folks,

This is a short one about documentation:

### Describe the bug

I believe the [dbt_header documentation](https://docs.getdbt.com/reference/resource-configs/sql_header#set-snowflake-session-parameters-for-all-models) is missing a semicolon at the end of the command to include in `dbt_project.yml`.

Not including the semicolon leads to a syntax error in dbt Cloud when running a Snowflake model (haven't tested other DBs).

The documentation should therefore read as:

```yaml
config-version: 2

models:
  +sql_header: "alter session set timezone = 'Australia/Sydney';"
```

Otherwise the following happens:

`syntax error line 3 at position 6 unexpected 'create'.` as the SQL command doesn't stop and try to execute the CREATE statement as part of the timezone header.

I believe that's all the info needed, it's pretty minor I think, let me know if you need anything else!

Thanks,

Guillaume
