### ISSUE TITLE
Cannot set store_failures as test modifier for unique, not_null

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt#3575]
### Describe the bug

Cannot set `store_failures` config on `unique` and `not_null` tests:
```yml
  - name: my_model
    columns: 
      - name: id
        tests:
          - not_null:
              store_failures: true # does not take effect
```

These built-in tests use an optimized codepath for test construction at parse time.

We either missed this in the original PR, or it got lost in the git merge/rebases. It's a super simple fix.

While here, I realized that I _think_ we're not doing `unrendered_config` quite right. That's a separate issue to look into. (edit: opened #3576)
