### ISSUE TITLE
`where` argument for relationship test produces invalid sql

### ISSUE THREAD

**Issue by jaypeedevlin** [dbt-labs/dbt#3579]
### Describe the bug
While testing out the new `where` config with a relationships test, I get a SQL complication error.  The issue seems to be that one of the subqueries is aliased twice, see below.

### Steps To Reproduce
- Find an existing relationships test
- Add `where: 1 = 1` as a config to the test
- Run the test.

### Expected behavior
The test to run without error.

### Screenshots and log output
For the following YAML:

```yaml
version: 2

models:
  - name: stg_jaffle_shop__orders
    description: "this is the orders table"
    columns:
      - name: customer_id
        tests:
          - relationships:
              to: stg_jaffle_shop__customers
              field: customer_id
              where: 1 = 1
```

The following is run against the DB

```sql
select
      count(*) as failures,
      count(*) != 0 as should_warn,
      count(*) != 0 as should_error
    from (
      
    
    

select
    child.customer_id

from (select * from JD_DBT.DEV_JOSH.stg_jaffle_shop__orders where 1 = 1) stg_jaffle_shop__orders as child

left join stg_jaffle_shop__customers as parent
    on child.customer_id = parent.customer_id

where child.customer_id is not null
  and parent.customer_id is null



      
    ) dbt_internal_test
```

The issue specifically seems to be the `stg_jaffle_shop__orders as child` where the table name is used as an alias and then it's attempt to be aliased again with `as child`.  The error returned is

```
  001003 (42000): SQL compilation error:
  syntax error line 13 at position 97 unexpected 'as'.
  syntax error line 24 at position 4 unexpected ')'.
  ```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.20.0
   latest version: 0.20.0

Up to date!

Plugins:
  - bigquery: 0.20.0
  - snowflake: 0.20.0
  - redshift: 0.20.0
  - postgres: 0.20.0
```

**The operating system you're using:** Mac

**The output of `python --version`:** Python 3.8.10
