### ISSUE TITLE
Adding descriptions to tests no longer possible with 0.20.0

### ISSUE THREAD

**Issue by mirosval** [dbt-labs/dbt#3599]
### Describe the bug
In 0.19 the following would work (in a Model or Source):

```yaml
     columns:
      - name: user_cohort
        tests:
          - not_null:
              severity: warn
              description: "severity reduced pending further investigation"
```

In 0.20 I get:
```
Runtime Error
  Compilation Error in test not_null_<test_name> (<model_yaml>)
    macro 'dbt_macro__test_not_null' takes no keyword argument 'description'

    > in macro test_not_null (macros/schema_tests/not_null.sql)
```

### Steps To Reproduce
Add `description: aaa` under a test in a model or source.

### Expected behavior
No compilation error

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.20.0
   latest version: 0.20.0

Up to date!

Plugins:
  - bigquery: 0.20.0
  - snowflake: 0.20.0
  - redshift: 0.20.0
  - postgres: 0.20.0

```

**The operating system you're using:** macOS 11.4

**The output of `python --version`:** 3.9.5

### Additional context
I have not found a mention of this in the release notes and to be fair the updated docs don't say this should be possible. But it did work before and I think its useful especially when you want to document why you downgraded a test to a warning instead of an error.
