### ISSUE TITLE
Add support for `meta` in tests

### ISSUE THREAD

**Issue by jtcohen6** [dbt-labs/dbt#3629]
### Describe the feature

Specific instances of generic tests should support meta properties:
```yml
models:
  - name: orders
    columns:
      - name: order_id
        tests:
          - not_null:
              where: "date > '2021-01-01'"
              meta:
                team: data
                service: "dbt"
                description: "I expect every order ID to be not null."
```

Should we try to do this in v0.20.1?
- Technically, tests used to support `meta` as a kwarg, and they no longer do. That's sort of a regression (along the lines of https://github.com/dbt-labs/dbt/issues/3599).
- The way that this worked was pretty weird and undocumented! I think the `meta` properties showed up only in `test_metadata.meta`, not in the node-level `meta` property (as they do for every other resource type).

If we wait until v0.21:
- #3616 will add support for `meta` as a config, settable in `dbt_project.yml`. Not yet in that PR: merging config-meta into property-meta
- From there, this could be as simple as adding support for `meta` as a test modifier
