### ISSUE TITLE
dbt packages.yml conflict: Found duplicate project "dbt_utils"

### ISSUE THREAD

**Issue by jsnb-devoted** [dbt-labs/dbt#3705]
### Describe the bug
`dbt deps` detects a duplicate project when installing package dependencies after upgrading to 0.20.0 (and upgrading the `dbt_utils` + `dbt_expectations` packages)

There is a note in the dbt_expectations [dbt hub page](https://hub.getdbt.com/calogica/dbt_expectations/latest/):
```
This package includes a reference to dbt-date which in turn references dbt-utils so there's no need to also import dbt-utils in your local project.
```
This seems to imply that I can just remove `dbt_utils` from my packages.yml file to resolve. Maybe that is the expected behavior?

### Steps To Reproduce
packages.yml file:
```
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.7.0
  - package: calogica/dbt_expectations
    version: 0.4.1
```
run `dbt deps`

```
Running with dbt=0.20.0
Encountered an error:
Found duplicate project "dbt_utils". This occurs when a dependency has the same project name as some other dependency.
```

### Expected behavior
Prior to upgrading the packages installed without error. I would have expected that `dbt deps` could resolve the dependencies between installed packages and the local project. I could imagine a scenario where we remove `dbt_expectations` and not know that we then have to add `dbt_utils` explicitly again. Not the end of the world but maybe a nice to have.

### Screenshots and log output
If applicable, add screenshots or log output to help explain your problem.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.20.0
   latest version: 0.20.0

Up to date!

Plugins:
  - postgres: 0.20.0
  - redshift: 0.20.0
  - snowflake: 0.20.0
  - bigquery: 0.20.0
```

**The operating system you're using:**
debian

**The output of `python --version`:**
`Python 3.8.8`

**Comment by jtcohen6** [comment]
Hey @jsnb-devoted, this should do the trick:
```yml
packages:
  - package: dbt-labs/dbt_utils
    version: 0.7.0
  - package: calogica/dbt_expectations
    version: 0.4.1
```

The error message you're seeing has to do with the company rename: `fishtown-analytics` &rarr; `dbt-labs`. In this case, `dbt_expectations` v0.4.1 requires `dbt-labs/dbt_utils`, your `packages.yml` explicitly requires `fishtown-analytics/dbt_utils`, and dbt isn't quite clever enough to know that those really redirect to the same thing.

Apologies for the annoyance, though I promise it's a one-time thing: while upgrading to dbt v0.20 and new package versions, users just need to switch the organization name as well. For more details: https://discourse.getdbt.com/t/packages-dbt-labs-in-the-dbt-hub/2711.

As you mention, because `dbt_expectations` requires `dbt_utils` (via `dbt_date`), you don't _need_ to include the `dbt_utils` requirement:
```yml
packages:
  - package: calogica/dbt_expectations
    version: 0.4.1
```
But I totally appreciate your point above, imagining a scenario where you may want to remove one and keep the other.
