### ISSUE TITLE
Allow for multiple source files or variables to be used in source files

### ISSUE THREAD

**Issue by Charles1104** [dbt-labs/dbt#3836]
### Describe the feature
As different databases can be used for different models either because:
1) different databases are used based on different environments
2) different databases are used to store all the different sources

### Describe alternatives you've considered
To tackle point 1, different targets per environment can be created and each of these targets then define the source database.

To tackle point 2, this would require to allow different databases to be specified and to change on top of this with the environment. Use of dbt variables within the source.yml file could solve this. Because for the moment, specific database can indeed be written within the source file but those are then frozen across targets so that mean that if a database is specified within a source file, it will be the same across targets. 

### Additional context
This is not database-specific.

### Who will this benefit?
Anyone that wants to have dynamic and multiple source database selection.

**Comment by jtcohen6** [comment]
@Charles1104 Could you say a bit more about what you're requesting / proposing?

You're right that, in the simplest case, dbt expects to point to the same source tables across environments/targets, though it's quite common on (e.g.) Snowflake to have sources located in different logical databases. Even then, it's quite possible to use env-aware Jinja expressions to point to different source tables.

I think a lot of what you're describing is possible today, via functionality like:
```yml
version: 2

sources:

  - name: my_source
    # same as target database
    database: "{{ target.database }}"
    tables: ...
    
  - name: my_other_source
    # set by var, with default defined in dbt_project.yml and possibility to override on CLI
    database: "{{ var('source_db_var') }}"
    tables: ...
    
  - name: my_additional_source
    # set by env var
    database: "{{ env_var('SOURCE_DB') }}"
    tables: ...
```
