### ISSUE TITLE
Relationship test is not triggered

### ISSUE THREAD

**Issue by leoch20** [dbt-labs/dbt#3903]
### Describe the bug
The relationship test does not get triggered

### Steps To Reproduce
`models/child.sql`

```sql
select 1 as parent_id, 1 as val
union
select 2 as parent_id, 2 as val
```
`models/parent.sql`
```sql
select 1 as id, 1 as val
```
`models/test.yml`
```yml
models:
  - name: child
    columns:
      - name: parent_id
        tests:
          - relationships:
              to: ref('parent')
              field: id

  - name: parent
    columns:
      - name: id
``` 
Create the models:
`dbt run -m parent child`

### Expected behavior
Running `dbt test -m child` should error out, but it does not. Although, running `dbt test -m parent child` does error out. 

### Screenshots and log output
```
WARNING: Nothing to do. Try checking your model configs and model specification args
```

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 0.20.1
   latest version: 0.20.2

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 0.20.1
  - snowflake: 0.20.1
  - redshift: 0.20.1
  - postgres: 0.20.1
```

**The operating system you're using:**
```
macOS Big Sur | version 11.4
```
**The output of `python --version`:**
```
Python 3.8.8
```
